name = "tapa-membership-portal"
main = "worker.js"
compatibility_date = "2026-08-01"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[vars]
ADMIN_EMAIL = "tapatobago@gmail.com"

[[d1_databases]]
binding="DB"
database_name="tapa-membership-db"
database_id="a40437c7-a7a9-4450-aacb-5d8a28c0f53a"
